steps:
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      echo "*************** TERRAFORM INIT ******************"
      echo "******* on branch: $BRANCH_NAME ********"
      echo "*************************************************"
      terraform init

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      echo "*************** TERRAFORM PLAN ******************"
      echo "******* on branch: $BRANCH_NAME ********"
      echo "*************************************************"
      terraform plan
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ $BRANCH_NAME = "master" ]; then 
        echo "*************** TERRAFORM APPLY ******************"
        echo "******* on branch: $BRANCH_NAME ********"
        echo "*************************************************" 
        terraform apply -auto-approve
      else
        echo "***************************** SKIPPING APPLYING *******************************"
        echo "Branch '$BRANCH_NAME' does not represent an official environment."
        echo "*******************************************************************************"
      fi
# [END tf-apply]      
